/* Generated By:JavaCC: Do not edit this line. ATreeConstants.java Version 5.0 */
public interface ATreeConstants
{
  public int JJTBLOCK = 0;
  public int JJTSIMPLE = 1;
  public int JJTVARIABLEDECLARATION = 2;
  public int JJTVARIABLEASSIGN = 3;
  public int JJTSTATEMENT = 4;
  public int JJTPROGRAM = 5;
  public int JJTEXPR = 6;
  public int JJTSUM = 7;
  public int JJTTERM = 8;
  public int JJTUNARY = 9;
  public int JJTELEMENT = 10;
  public int JJTIDENTIFIER = 11;


  public String[] jjtNodeName = {
    "block",
    "simple",
    "VariableDeclaration",
    "VariableAssign",
    "statement",
    "program",
    "expr",
    "sum",
    "term",
    "unary",
    "element",
    "identifier",
  };
}
/* JavaCC - OriginalChecksum=41d2c0396da2b414091afec7ab966926 (do not edit this line) */
